# -*- python -*-

Import("env")

plugin = env.SharedLibrary(
    target = "jsonrpc-remote",
    source = ["src/server.cpp", "src/plugin.cpp"],
    CPPPATH = env["CPPPATH"] + [Dir("src")]
)

env["PLUGINS"].append(plugin)

env.Alias("install", env.Install("$PREFIX/usr/lib/zeppelin/plugins", plugin))
