# -*- python -*-

Import("env")

plugin = env.SharedLibrary(
    target = "jsonrpc-remote",
    source = ["src/server.cpp", "src/plugin.cpp"],
    CPPPATH = env["CPPPATH"] + [Dir("#../libjson-rpc-cpp-lib/include"), Dir("src")],
    LIBPATH = [Dir("#../libjson-rpc-cpp-lib/lib")]
)

env["PLUGINS"].append(plugin)
