# This file is part of the Zeppelin music player project.
# Copyright (c) 2013-2014 Zoltan Kovacs, Lajos Santa
# See http://zeppelin-player.com for more details.

Import("env")

SConscript(dirs = ["debian"], exports = ["env"])
