# -*- python -*-

Import("env")

plugin = env.SharedLibrary(
    target = "file-server",
    source = ["src/plugin.cpp", "src/fileserver.cpp"],
    CPPPATH = env["CPPPATH"] + [Dir("src")]
)

env["PLUGINS"].append(plugin)

env.Alias("install", env.Install("$PREFIX/usr/lib/zeppelin/plugins", plugin))
